### ISSUE TITLE
10000 Call Update

### ISSUE THREAD

**Issue by O-S-K** [pancake-llc/foundation#150]
i have read the article https://unity.com/blog/engine-platform/10000-update-calls
and i tried it but really didn't see any difference did i do something wrong, when i tested in 2 updates i ++ it seems that UpdateMono is 4 times better than Update, but when i process like adding code like string hello:
Debug.Log("Hello") in UpdateMono and Update it seems that UpdateMono creates more garbage and processes slower, similarly adding other commands like set rotation angle scale position... it's the same
![22222](https://github.com/user-attachments/assets/449f6dff-5575-4c07-bf2c-a6b0b3e868d2)

**Comment by aprius** [comment]
You can refer to the benchmarks listed [here](https://github.com/pancake-llc/foundation/wiki/benchmark-managed-update) for comparison.

**Comment by aprius** [comment]
Using a profiler would be inaccurate in this case because Unity's profiler typically aggregates all calls of the same function (e.g. MonoBehaviour.Update) into one aggregate entry. This makes it difficult to directly compare UpdateManager and 1000 individual Updates, since the total time for each function is unclear.

In theory

- UpdateManager: There is usually only one call to Update in the game loop, then the logic is managed through lists or delegates. This reduces the overhead of Unity Message Dispatch.

- 1000 Update: Unity must call each Update function on each `GameObject`, leading to additional overhead from internal message distribution.

**Comment by O-S-K** [comment]
Thank you for your reply, I am reassured and do I need to pay attention to anything when using it?

**Comment by aprius** [comment]
If you design it right then there is nothing to worry about if you implement it yourself then pay attention to the execution order and manage the lifecycle of the subscriptions

**Comment by O-S-K** [comment]
![image](https://github.com/user-attachments/assets/f2a27c5e-12f9-4ea2-a418-f9030de53b37)

I have a question, why do I have to sub 3 at once? If I just want to update the tick, will adding fixtick vs latetick to the array reduce performance? Thank you.

**Comment by IAFahim** [comment]
You don't have to inherit from it. You can just `App.AddListners` from any class.
