### ISSUE TITLE
GameObjectPool.Request() Runs OnEnable twice. Is it bug or by design?

### ISSUE THREAD

**Issue by IAFahim** [pancake-llc/foundation#39]
```
public override GameObject Request()
{
    var member = base.Request();
    member.gameObject.SetActive(true);
    return member;
}
 ```
 Which Runs create which sets gameobject False
 
 ```
protected override GameObject Create()
{
    var member = base.Create();
    member.transform.SetParent(Root);
    member.gameObject.SetActive(false);
    return member;
}
```
And Again when factory method is called it gets instantiated and set as active

![image](https://github.com/pancake-llc/foundation/assets/63500913/a957db1e-9d6a-42e0-a2b1-72ff24cd7eaf)

Problem it creates:
Enable logic and disable logic runs 2 times

**Comment by yenmoc** [comment]
Yes, that's right, OnEnable will be called twice for the first time the GameObject is created. This is because your initial prefab is set to active state and the Create function will always change the state to deactive (to be able to prewarm) because So if you Request GameObject without Prewarm or the pool is empty then you will get OnEnable called twice. To avoid this you can set your prefab state to false from the beginning or check the condition in OnEnable to ensure Tells the init code not to be called twice if it has already been inited
